# Generated by Django 4.1.13 on 2024-02-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ejemplo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('var1', models.CharField(max_length=30)),
                ('var2', models.CharField(max_length=30)),
            ],
        ),
    ]
