# Generated by Django 4.1.13 on 2024-02-23 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('offer_type', models.CharField(choices=[('CO', 'COMPAÑÍA'), ('CU', 'CUIDADO'), ('TR', 'TRANSPORTE'), ('DO', 'COMPRA A DOMICILIO'), ('OT', 'OTROS')], default='OT', max_length=255, verbose_name='Tipo de oferta')),
                ('client', models.CharField(choices=[('DF', 'DISCAPACIDAD FÍSICA'), ('DM', 'DISCAPACIDAD MENTAL'), ('NI', 'NIÑOS'), ('AN', 'ANCIANOS'), ('OT', 'OTROS')], default='OT', max_length=255, verbose_name='Tipo de cliente')),
                ('description', models.TextField(blank=True)),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('city', models.CharField(max_length=200, verbose_name='Ciudad')),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
