# Generated by Django 4.1.13 on 2024-02-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='username',
            field=models.CharField(default='cuidador', max_length=200, verbose_name='username'),
        ),
    ]
