# Generated by Django 4.1.1 on 2024-03-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='city',
        ),
        migrations.AddField(
            model_name='offer',
            name='poblacion',
            field=models.CharField(choices=[('Alcalá de Guadaíra', 'Alcalá de Guadaíra'), ('Dos Hermanas', 'Dos Hermanas'), ('Écija', 'Écija'), ('Mairena del Aljarafe', 'Mairena del Aljarafe'), ('sevilla', 'sevilla')], default='sevilla', max_length=200, verbose_name='Población'),
        ),
    ]
