# Generated by Django 4.1.13 on 2024-02-24 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('offer', '0002_offer_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='username',
        ),
        migrations.AddField(
            model_name='offer',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
