# Generated by Django 4.1.13 on 2024-02-24 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0003_remove_offer_username_offer_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='usuario',
            new_name='user',
        ),
    ]
