# Generated by Django 4.1.13 on 2024-02-26 10:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0004_rename_usuario_offer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
