# Generated by Django 4.2.7 on 2024-03-03 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0006_chatrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatrequest',
            old_name='timeSend',
            new_name='time_Send',
        ),
    ]
