# Generated by Django 4.1.1 on 2024-02-29 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '__first__'),
        ('offer', '0006_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='offer',
        ),
        migrations.AddField(
            model_name='review',
            name='cuidador',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.cuidador'),
            preserve_default=False,
        ),
    ]
