# Generated by Django 4.1.1 on 2024-02-29 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0007_remove_review_offer_review_cuidador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='cuidador',
        ),
        migrations.AddField(
            model_name='review',
            name='offer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='offer.offer'),
            preserve_default=False,
        ),
    ]
