# Generated by Django 4.1.1 on 2024-03-01 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0008_remove_review_cuidador_review_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='offer.offer'),
        ),
        migrations.AlterModelTable(
            name='offer',
            table='offer_offer',
        ),
        migrations.AlterModelTable(
            name='review',
            table='offer_review',
        ),
    ]
