# Generated by Django 4.1.1 on 2024-03-01 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0009_alter_review_offer_alter_offer_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='average_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offer.offer'),
        ),
        migrations.AlterModelTable(
            name='offer',
            table=None,
        ),
        migrations.AlterModelTable(
            name='review',
            table=None,
        ),
    ]
