# Generated by Django 4.1.1 on 2024-03-01 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0010_offer_average_rating_alter_review_offer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='Total_average_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='offer',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
