# Generated by Django 4.1.1 on 2024-03-01 23:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0011_offer_total_average_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='Total_average_rating',
            new_name='total_average_rating',
        ),
        migrations.AlterField(
            model_name='review',
            name='valoration',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
