# Generated by Django 4.1.1 on 2024-03-23 11:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_bool', models.BooleanField(default=False)),
                ('stripe_checkout_id', models.CharField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cuidador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_perfil', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
                ('dni', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Introduce un DNI válido (8 dígitos seguidos de una letra)', regex='^[0-9]{8}[A-Za-z]$')])),
                ('numero_seguridad_social', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Introduce un número de seguridad social válido (12 dígitos)', regex='^[0-9]{12}$')])),
                ('descripcion', models.TextField()),
                ('fecha_nacimiento', models.DateField()),
                ('formacion', models.TextField()),
                ('tipo_publico_dirigido', models.CharField(choices=[('DF', 'DISCAPACIDAD FÍSICA'), ('DM', 'DISCAPACIDAD MENTAL'), ('NI', 'NIÑOS'), ('AN', 'ANCIANOS'), ('OT', 'OTROS')], default='OT', max_length=50)),
                ('Total_average_rating', models.FloatField(default=0)),
                ('chat_requests_received', models.ManyToManyField(related_name='caregiver_received_requests', to='chat.chatrequest')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_perfil', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
                ('apellidos', models.CharField(max_length=100)),
                ('tipo_dependencia', models.CharField(choices=[('personaSolitaria', 'Persona Solitaria'), ('enfermedad', 'Enfermedad'), ('cuidados', 'Cuidados')], max_length=20)),
                ('chat_requests_sent', models.ManyToManyField(related_name='client_sent_requests', to='chat.chatrequest')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
