# Generated by Django 4.1.1 on 2024-03-20 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='tipo_dependencia',
        ),
        migrations.RemoveField(
            model_name='cuidador',
            name='tipo_publico_dirigido',
        ),
        migrations.CreateModel(
            name='Interes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_type', models.CharField(choices=[('CO', 'COMPAÑÍA'), ('CU', 'CUIDADO'), ('TR', 'TRANSPORTE'), ('DO', 'COMPRA A DOMICILIO'), ('OT', 'OTROS')], default='OT', max_length=255, verbose_name='Tipo de oferta')),
                ('client', models.CharField(choices=[('DF', 'DISCAPACIDAD FÍSICA'), ('DM', 'DISCAPACIDAD MENTAL'), ('NI', 'NIÑOS'), ('AN', 'ANCIANOS'), ('OT', 'OTROS')], default='OT', max_length=255, verbose_name='Tipo de cliente')),
                ('poblacion', models.CharField(max_length=200, verbose_name='Población')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.userpayment')),
            ],
        ),
    ]
