# Generated by Django 4.2.7 on 2024-03-02 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0006_chatrequest'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='chat_requests_sent',
            field=models.ManyToManyField(related_name='client_sent_requests', to='offer.chatrequest'),
        ),
        migrations.AddField(
            model_name='cuidador',
            name='chat_requests_received',
            field=models.ManyToManyField(related_name='caregiver_received_requests', to='offer.chatrequest'),
        ),
    ]
