# Generated by Django 4.2.7 on 2024-03-01 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='chat_requests_sent',
        ),
        migrations.RemoveField(
            model_name='cuidador',
            name='chat_requests_received',
        ),
        migrations.DeleteModel(
            name='ChatRequest',
        ),
    ]
