# Generated by Django 4.1.1 on 2024-03-21 11:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='imagen_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
        migrations.AddField(
            model_name='cuidador',
            name='imagen_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
        migrations.AlterField(
            model_name='cuidador',
            name='dni',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Introduce un DNI válido (8 dígitos seguidos de una letra)', regex='^[0-9]{8}[A-Za-z]$')]),
        ),
        migrations.AlterField(
            model_name='cuidador',
            name='numero_seguridad_social',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Introduce un número de seguridad social válido (12 dígitos)', regex='^[0-9]{12}$')]),
        ),
        migrations.AlterField(
            model_name='cuidador',
            name='tipo_publico_dirigido',
            field=models.CharField(choices=[('DF', 'DISCAPACIDAD FÍSICA'), ('DM', 'DISCAPACIDAD MENTAL'), ('NI', 'NIÑOS'), ('AN', 'ANCIANOS'), ('OT', 'OTROS')], default='OT', max_length=50),
        ),
    ]
