# Generated by Django 4.1.1 on 2024-03-09 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_userpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuidador',
            name='Total_average_rating',
            field=models.FloatField(default=0),
        ),
    ]
