# Generated by Django 4.1.1 on 2024-03-16 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_userpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuidador',
            name='tipo_publico_dirigido',
            field=models.CharField(choices=[('personaSolitaria', 'Persona Solitaria'), ('enfermedad', 'Enfermedad'), ('cuidados', 'Cuidados')], max_length=100),
        ),
    ]
