# Generated by Django 4.1.1 on 2024-03-16 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_cuidador_tipo_publico_dirigido'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='imagen_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='clientesImagen/'),
        ),
        migrations.AddField(
            model_name='cuidador',
            name='imagen_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='cuidadoresImagen/'),
        ),
    ]
