# Generated by Django 4.1.1 on 2024-03-16 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_cuidador_dni_alter_cuidador_imagen_perfil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='imagen_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes'),
        ),
        migrations.AlterField(
            model_name='cuidador',
            name='imagen_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes'),
        ),
    ]
