# Generated by Django 4.1.1 on 2024-03-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_cliente_imagen_perfil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='imagen_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
        migrations.AlterField(
            model_name='cuidador',
            name='imagen_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
    ]
